version: '3'
services:
    node:
        build: .
        ports:
            - '3030:3000'
        volumes:
            - ./app:/srv/app
        container_name: react-drag-drop
        # command: node /srv/app/app.js
        command: npm start --prefix /srv/app/drag-drop
