const dispatches = {
    ADD_NEW_BLOCK : "ADD_NEW_BLOCK",
    ADD_DRAGGABLE_ELEMENT: "ADD_DRAGGABLE_ELEMENT",
    REMOVE_DRAGGABLE_ELEMENT: "REMOVE_DRAGGABLE_ELEMENT",
    ADD_DRAG_OVER: "ADD_DRAG_OVER",
    REMOVE_DRAG_OVER: "REMOVE_DRAG_OVER",
}

export default dispatches;
